directory: ~/Music
library: ~/.config/beets/musiclibrary.blb
plugins: fromfilename ftintitle fetchart embedart edit mpdupdate

import:
    # Don't copy files but move them
    move: yes

fetchart:
    sources: filesystem coverart amazon albumart wikipedia

embedart:
    auto: yes

mpdupdate:
    host: localhost
    port: 6600
